/**
 * Provider-neutral AI entry point for new SEO Operating System workflows.
 *
 * Existing backlink recommendation may keep using its current OpenAI helper
 * until parity is verified. New workflows should call runAiJson() instead of
 * importing a provider-specific SDK/helper from UI or feature modules.
 *
 * Factual SEO metrics must never be generated by this layer.
 */

import { isOpenAiConfigured, openAiJson } from "@/lib/seo/openai.server";
import type { AiJsonRequest, AiJsonResult, AiProvider, AiProviderName } from "./types";

const openAiProvider: AiProvider = {
  name: "openai",
  isConfigured: isOpenAiConfigured,
  async json<T>(request: AiJsonRequest) {
    return openAiJson<T>(request);
  },
};

const providers: Partial<Record<AiProviderName, AiProvider>> = {
  openai: openAiProvider,
};

export function configuredAiProviderName(): AiProviderName {
  const requested = String(process.env["AI_PROVIDER"] ?? "openai").toLowerCase();
  return requested === "lovable" ? "lovable" : "openai";
}

export function getAiProvider(name = configuredAiProviderName()): AiProvider | null {
  return providers[name] ?? null;
}

export async function runAiJson<T>(request: AiJsonRequest): Promise<AiJsonResult<T>> {
  const providerName = configuredAiProviderName();
  const provider = getAiProvider(providerName);

  if (!provider) {
    return {
      data: null,
      error:
        `AI provider "${providerName}" belum memiliki adapter yang terverifikasi. ` +
        "Gunakan AI_PROVIDER=openai sampai adapter tersebut selesai diuji.",
      provider: providerName,
    };
  }

  if (!provider.isConfigured()) {
    return {
      data: null,
      error: `AI provider "${provider.name}" belum dikonfigurasi di server.`,
      provider: provider.name,
    };
  }

  const result = await provider.json<T>(request);
  return { ...result, provider: provider.name };
}
