/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDomainResearchRouteImport } from './routes/_authenticated/domain-research'
import { Route as AuthenticatedKeywordResearchRouteImport } from './routes/_authenticated/keyword-research'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedSeoPhase2TestRouteImport } from './routes/_authenticated/seo-phase2-test'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTestSearchVolumeRouteImport } from './routes/_authenticated/test-search-volume'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainResearchRoute =
  AuthenticatedDomainResearchRouteImport.update({
    id: '/domain-research',
    path: '/domain-research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeywordResearchRoute =
  AuthenticatedKeywordResearchRouteImport.update({
    id: '/keyword-research',
    path: '/keyword-research',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoPhase2TestRoute =
  AuthenticatedSeoPhase2TestRouteImport.update({
    id: '/seo-phase2-test',
    path: '/seo-phase2-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestSearchVolumeRoute =
  AuthenticatedTestSearchVolumeRouteImport.update({
    id: '/test-search-volume',
    path: '/test-search-volume',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/domain-research': typeof AuthenticatedDomainResearchRoute
  '/keyword-research': typeof AuthenticatedKeywordResearchRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/seo-phase2-test': typeof AuthenticatedSeoPhase2TestRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/test-search-volume': typeof AuthenticatedTestSearchVolumeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/domain-research': typeof AuthenticatedDomainResearchRoute
  '/keyword-research': typeof AuthenticatedKeywordResearchRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/seo-phase2-test': typeof AuthenticatedSeoPhase2TestRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/test-search-volume': typeof AuthenticatedTestSearchVolumeRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/domain-research': typeof AuthenticatedDomainResearchRoute
  '/_authenticated/keyword-research': typeof AuthenticatedKeywordResearchRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/seo-phase2-test': typeof AuthenticatedSeoPhase2TestRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/test-search-volume': typeof AuthenticatedTestSearchVolumeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/domain-research'
    | '/keyword-research'
    | '/projects'
    | '/seo-phase2-test'
    | '/settings'
    | '/test-search-volume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/domain-research'
    | '/keyword-research'
    | '/projects'
    | '/seo-phase2-test'
    | '/settings'
    | '/test-search-volume'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/domain-research'
    | '/_authenticated/keyword-research'
    | '/_authenticated/projects'
    | '/_authenticated/seo-phase2-test'
    | '/_authenticated/settings'
    | '/_authenticated/test-search-volume'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domain-research': {
      id: '/_authenticated/domain-research'
      path: '/domain-research'
      fullPath: '/domain-research'
      preLoaderRoute: typeof AuthenticatedDomainResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keyword-research': {
      id: '/_authenticated/keyword-research'
      path: '/keyword-research'
      fullPath: '/keyword-research'
      preLoaderRoute: typeof AuthenticatedKeywordResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo-phase2-test': {
      id: '/_authenticated/seo-phase2-test'
      path: '/seo-phase2-test'
      fullPath: '/seo-phase2-test'
      preLoaderRoute: typeof AuthenticatedSeoPhase2TestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test-search-volume': {
      id: '/_authenticated/test-search-volume'
      path: '/test-search-volume'
      fullPath: '/test-search-volume'
      preLoaderRoute: typeof AuthenticatedTestSearchVolumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDomainResearchRoute: typeof AuthenticatedDomainResearchRoute
  AuthenticatedKeywordResearchRoute: typeof AuthenticatedKeywordResearchRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSeoPhase2TestRoute: typeof AuthenticatedSeoPhase2TestRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTestSearchVolumeRoute: typeof AuthenticatedTestSearchVolumeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDomainResearchRoute: AuthenticatedDomainResearchRoute,
  AuthenticatedKeywordResearchRoute: AuthenticatedKeywordResearchRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSeoPhase2TestRoute: AuthenticatedSeoPhase2TestRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTestSearchVolumeRoute: AuthenticatedTestSearchVolumeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
