export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      app_workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          role?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          role?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      app_workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      backlinks: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          placement_order_id: string | null;
          source_domain: string;
          source_url: string | null;
          target_url: string | null;
          keyword: string | null;
          anchor_text: string | null;
          link_type: string;
          status: string;
          dr: number | null;
          traffic: number | null;
          first_seen_at: string | null;
          last_checked_at: string | null;
          created_at: string;
          updated_at: string;
          workspace_id: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          placement_order_id?: string | null;
          source_domain: string;
          source_url?: string | null;
          target_url?: string | null;
          keyword?: string | null;
          anchor_text?: string | null;
          link_type?: string;
          status?: string;
          dr?: number | null;
          traffic?: number | null;
          first_seen_at?: string | null;
          last_checked_at?: string | null;
          created_at?: string;
          updated_at?: string;
          workspace_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          placement_order_id?: string | null;
          source_domain?: string;
          source_url?: string | null;
          target_url?: string | null;
          keyword?: string | null;
          anchor_text?: string | null;
          link_type?: string;
          status?: string;
          dr?: number | null;
          traffic?: number | null;
          first_seen_at?: string | null;
          last_checked_at?: string | null;
          created_at?: string;
          updated_at?: string;
          workspace_id?: string | null;
        };
        Relationships: [];
      };
      check_logs: {
        Row: {
          id: string;
          domain: string;
          hasil: string;
          dr: number | null;
          traffic: number | null;
          pesan: string | null;
          created_at: string;
          user_id: string | null;
        };
        Insert: {
          id?: string;
          domain: string;
          hasil: string;
          dr?: number | null;
          traffic?: number | null;
          pesan?: string | null;
          created_at?: string;
          user_id?: string | null;
        };
        Update: {
          id?: string;
          domain?: string;
          hasil?: string;
          dr?: number | null;
          traffic?: number | null;
          pesan?: string | null;
          created_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      data_imports: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string | null;
          module: string;
          source_type: string;
          original_filename: string | null;
          mapping: Json;
          normalization_summary: Json;
          status: string;
          error: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          project_id?: string | null;
          module: string;
          source_type?: string;
          original_filename?: string | null;
          mapping?: Json;
          normalization_summary?: Json;
          status?: string;
          error?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          project_id?: string | null;
          module?: string;
          source_type?: string;
          original_filename?: string | null;
          mapping?: Json;
          normalization_summary?: Json;
          status?: string;
          error?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      domain_sudah_pernah: {
        Row: {
          id: string;
          domain: string;
          dr: number | null;
          traffic: number | null;
          checked_at: string;
          status: string;
          notes: string | null;
          created_at: string;
          user_id: string | null;
          keyword: string | null;
          target_page: string | null;
          purchase_date: string | null;
          price: number | null;
          research_status: string;
        };
        Insert: {
          id?: string;
          domain: string;
          dr?: number | null;
          traffic?: number | null;
          checked_at?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          user_id?: string | null;
          keyword?: string | null;
          target_page?: string | null;
          purchase_date?: string | null;
          price?: number | null;
          research_status?: string;
        };
        Update: {
          id?: string;
          domain?: string;
          dr?: number | null;
          traffic?: number | null;
          checked_at?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          user_id?: string | null;
          keyword?: string | null;
          target_page?: string | null;
          purchase_date?: string | null;
          price?: number | null;
          research_status?: string;
        };
        Relationships: [];
      };
      global_domain_cache: {
        Row: {
          id: string;
          normalized_domain: string;
          dr: number | null;
          traffic: number | null;
          backlinks: number | null;
          referring_domains: number | null;
          top_keywords: Json | null;
          top_pages: Json | null;
          provider: string;
          authority_checked_at: string | null;
          traffic_checked_at: string | null;
          raw_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          normalized_domain: string;
          dr?: number | null;
          traffic?: number | null;
          backlinks?: number | null;
          referring_domains?: number | null;
          top_keywords?: Json | null;
          top_pages?: Json | null;
          provider?: string;
          authority_checked_at?: string | null;
          traffic_checked_at?: string | null;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          normalized_domain?: string;
          dr?: number | null;
          traffic?: number | null;
          backlinks?: number | null;
          referring_domains?: number | null;
          top_keywords?: Json | null;
          top_pages?: Json | null;
          provider?: string;
          authority_checked_at?: string | null;
          traffic_checked_at?: string | null;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      keyword_metrics_cache: {
        Row: {
          id: string;
          keyword: string;
          normalized_keyword: string;
          country: string;
          search_volume: number | null;
          keyword_difficulty: number | null;
          cpc: number | null;
          traffic_potential: number | null;
          provider: string;
          checked_at: string;
          raw_data: Json | null;
          created_at: string;
          updated_at: string;
          language: string;
        };
        Insert: {
          id?: string;
          keyword: string;
          normalized_keyword: string;
          country?: string;
          search_volume?: number | null;
          keyword_difficulty?: number | null;
          cpc?: number | null;
          traffic_potential?: number | null;
          provider?: string;
          checked_at?: string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
          language?: string;
        };
        Update: {
          id?: string;
          keyword?: string;
          normalized_keyword?: string;
          country?: string;
          search_volume?: number | null;
          keyword_difficulty?: number | null;
          cpc?: number | null;
          traffic_potential?: number | null;
          provider?: string;
          checked_at?: string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
          language?: string;
        };
        Relationships: [];
      };
      keyword_rank_cache: {
        Row: {
          id: string;
          target_domain: string;
          keyword: string;
          normalized_keyword: string;
          country: string;
          position: number | null;
          ranking_url: string | null;
          ranking_title: string | null;
          traffic: number | null;
          dr: number | null;
          ur: number | null;
          provider: string;
          checked_at: string;
          raw_data: Json | null;
          created_at: string;
          updated_at: string;
          language: string;
        };
        Insert: {
          id?: string;
          target_domain: string;
          keyword: string;
          normalized_keyword: string;
          country?: string;
          position?: number | null;
          ranking_url?: string | null;
          ranking_title?: string | null;
          traffic?: number | null;
          dr?: number | null;
          ur?: number | null;
          provider?: string;
          checked_at?: string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
          language?: string;
        };
        Update: {
          id?: string;
          target_domain?: string;
          keyword?: string;
          normalized_keyword?: string;
          country?: string;
          position?: number | null;
          ranking_url?: string | null;
          ranking_title?: string | null;
          traffic?: number | null;
          dr?: number | null;
          ur?: number | null;
          provider?: string;
          checked_at?: string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
          language?: string;
        };
        Relationships: [];
      };
      placement_orders: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          source_domain: string;
          target_url: string | null;
          keyword: string | null;
          anchor_text: string | null;
          status: string;
          price: number | null;
          placed_at: string | null;
          notes: string | null;
          dr: number | null;
          traffic: number | null;
          search_volume: number | null;
          created_at: string;
          updated_at: string;
          workspace_id: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          source_domain: string;
          target_url?: string | null;
          keyword?: string | null;
          anchor_text?: string | null;
          status?: string;
          price?: number | null;
          placed_at?: string | null;
          notes?: string | null;
          dr?: number | null;
          traffic?: number | null;
          search_volume?: number | null;
          created_at?: string;
          updated_at?: string;
          workspace_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          source_domain?: string;
          target_url?: string | null;
          keyword?: string | null;
          anchor_text?: string | null;
          status?: string;
          price?: number | null;
          placed_at?: string | null;
          notes?: string | null;
          dr?: number | null;
          traffic?: number | null;
          search_volume?: number | null;
          created_at?: string;
          updated_at?: string;
          workspace_id?: string | null;
        };
        Relationships: [];
      };
      project_data_sources: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string;
          source_key: string;
          status: string;
          notes: string | null;
          updated_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          project_id: string;
          source_key: string;
          status?: string;
          notes?: string | null;
          updated_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          project_id?: string;
          source_key?: string;
          status?: string;
          notes?: string | null;
          updated_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_evidence: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string | null;
          created_by: string;
          source_type: string;
          title: string | null;
          original_filename: string | null;
          mime_type: string | null;
          storage_path: string | null;
          source_url: string | null;
          raw_text: string | null;
          extracted_metadata: Json;
          processing_status: string;
          processing_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          project_id?: string | null;
          created_by?: string;
          source_type?: string;
          title?: string | null;
          original_filename?: string | null;
          mime_type?: string | null;
          storage_path?: string | null;
          source_url?: string | null;
          raw_text?: string | null;
          extracted_metadata?: Json;
          processing_status?: string;
          processing_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          project_id?: string | null;
          created_by?: string;
          source_type?: string;
          title?: string | null;
          original_filename?: string | null;
          mime_type?: string | null;
          storage_path?: string | null;
          source_url?: string | null;
          raw_text?: string | null;
          extracted_metadata?: Json;
          processing_status?: string;
          processing_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_field_suggestions: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string;
          run_id: string | null;
          field: string;
          suggested_value: string;
          rationale: string | null;
          status: string;
          decided_by: string | null;
          decided_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          project_id: string;
          run_id?: string | null;
          field: string;
          suggested_value: string;
          rationale?: string | null;
          status?: string;
          decided_by?: string | null;
          decided_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          project_id?: string;
          run_id?: string | null;
          field?: string;
          suggested_value?: string;
          rationale?: string | null;
          status?: string;
          decided_by?: string | null;
          decided_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_intelligence_runs: {
        Row: {
          id: string;
          workspace_id: string;
          project_id: string;
          provider: string;
          model: string | null;
          status: string;
          error: string | null;
          input_summary: Json;
          output: Json;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          project_id: string;
          provider?: string;
          model?: string | null;
          status?: string;
          error?: string | null;
          input_summary?: Json;
          output?: Json;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          project_id?: string;
          provider?: string;
          model?: string | null;
          status?: string;
          error?: string | null;
          input_summary?: Json;
          output?: Json;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          client_domain: string | null;
          description: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          workspace_id: string | null;
          lifecycle_status: string;
          activated_at: string | null;
          industry: string | null;
          objectives: string[];
          target_market: string | null;
          current_problem: string | null;
          contact_person: string | null;
          budget_indication: string | null;
          competitors: string[];
          discovery_notes: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          name: string;
          client_domain?: string | null;
          description?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          workspace_id?: string | null;
          lifecycle_status?: string;
          activated_at?: string | null;
          industry?: string | null;
          objectives?: string[];
          target_market?: string | null;
          current_problem?: string | null;
          contact_person?: string | null;
          budget_indication?: string | null;
          competitors?: string[];
          discovery_notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          client_domain?: string | null;
          description?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          workspace_id?: string | null;
          lifecycle_status?: string;
          activated_at?: string | null;
          industry?: string | null;
          objectives?: string[];
          target_market?: string | null;
          current_problem?: string | null;
          contact_person?: string | null;
          budget_indication?: string | null;
          competitors?: string[];
          discovery_notes?: string | null;
        };
        Relationships: [];
      };
      search_history: {
        Row: {
          id: string;
          user_id: string | null;
          query: string;
          normalized_query: string;
          search_count: number;
          first_searched_at: string;
          last_searched_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          query: string;
          normalized_query: string;
          search_count?: number;
          first_searched_at?: string;
          last_searched_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          query?: string;
          normalized_query?: string;
          search_count?: number;
          first_searched_at?: string;
          last_searched_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      seo_research_runs: {
        Row: {
          id: string;
          provider: string;
          search_type: string;
          query: string | null;
          cache_hit: boolean;
          status: string;
          result_count: number | null;
          error: string | null;
          duration_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          provider?: string;
          search_type: string;
          query?: string | null;
          cache_hit?: boolean;
          status?: string;
          result_count?: number | null;
          error?: string | null;
          duration_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          search_type?: string;
          query?: string | null;
          cache_hit?: boolean;
          status?: string;
          result_count?: number | null;
          error?: string | null;
          duration_ms?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      sudah_dibeli: {
        Row: {
          id: string;
          domain: string;
          dr: number | null;
          traffic: number | null;
          checked_at: string;
          status: string;
          notes: string | null;
          created_at: string;
          user_id: string | null;
          keyword: string | null;
          target_page: string | null;
          purchase_date: string | null;
          price: number | null;
          research_status: string;
          search_volume: number | null;
        };
        Insert: {
          id?: string;
          domain: string;
          dr?: number | null;
          traffic?: number | null;
          checked_at?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          user_id?: string | null;
          keyword?: string | null;
          target_page?: string | null;
          purchase_date?: string | null;
          price?: number | null;
          research_status?: string;
          search_volume?: number | null;
        };
        Update: {
          id?: string;
          domain?: string;
          dr?: number | null;
          traffic?: number | null;
          checked_at?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          user_id?: string | null;
          keyword?: string | null;
          target_page?: string | null;
          purchase_date?: string | null;
          price?: number | null;
          research_status?: string;
          search_volume?: number | null;
        };
        Relationships: [];
      };
      traffic_nol: {
        Row: {
          id: string;
          domain: string;
          dr: number | null;
          traffic: number;
          checked_at: string;
          status: string;
          notes: string | null;
          created_at: string;
          user_id: string | null;
          research_status: string;
        };
        Insert: {
          id?: string;
          domain: string;
          dr?: number | null;
          traffic?: number;
          checked_at?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          user_id?: string | null;
          research_status?: string;
        };
        Update: {
          id?: string;
          domain?: string;
          dr?: number | null;
          traffic?: number;
          checked_at?: string;
          status?: string;
          notes?: string | null;
          created_at?: string;
          user_id?: string | null;
          research_status?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      is_workspace_member: { Args: { _workspace_id: string }; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
